import { Listing } from '@/types';

// Helper shared fields
const baseHours = {
  monday: { open: '09:00', close: '18:00' },
  tuesday: { open: '09:00', close: '18:00' },
  wednesday: { open: '09:00', close: '18:00' },
  thursday: { open: '09:00', close: '18:00' },
  friday: { open: '09:00', close: '18:00' },
  saturday: { open: '10:00', close: '16:00' },
  sunday: { closed: true },
};

const baseMockListings: Listing[] = [
  // 10 Published
  {
    id: '1',
    organization_id: 'org1',
    slug: 'premium-coffee-shop',
    title: 'Premium Coffee Shop',
    tagline: 'Artisanal coffee crafted with passion',
    description: 'We source our beans directly from farmers and roast them fresh daily. Experience quality and sustainability.',
    category: 'Food & Beverage',
    tags: ['coffee', 'pastries', 'wifi', 'sustainable'],
    location: { province: 'Western Area', district: 'Western Area Urban', chiefdom: 'Freetown' },
    district: 'Western Area Urban',
    chiefdom: 'Freetown',
    full_address: '1 Cocoa St, Freetown',
    business_hours: baseHours,
    price_range: 'moderate',
    logo_url: 'https://api.dicebear.com/7.x/initials/svg?seed=Premium%20Coffee%20Shop',
    images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&auto=format&fit=crop'],
    videos: [],
    faqs: [
      { id: 'f1', question: 'Do you offer WiFi?', answer: 'Yes, free WiFi for customers.', order: 1 },
    ],
    announcements: [
      { id: 'a1', title: 'Winter Menu', content: 'Try our seasonal drinks!', type: 'info', active: true, created_at: '2024-01-20T10:00:00Z' },
    ],
    deals: [
      { id: 'd1', title: 'Happy Hour', description: '50% off 3-5 PM', discount_type: 'percentage', discount_value: 50, valid_from: '2024-01-01', valid_until: '2024-12-31', current_uses: 12, active: true },
    ],
    menu: [
      { id: 'm1', name: 'Espresso', price: 2.5, category: 'Coffee', available: true },
    ],
    events: [],
    contact_email: 'info@premiumcoffee.com',
    contact_phone: '+232-76-000001',
    whatsapp_number: '+232-76-000001',
    website_url: 'https://premiumcoffee.com',
    contact_person: { full_name: 'John Doe' },
    target_audience: ['coffee lovers', 'students'],
    social_links: { facebook: 'https://facebook.com/premiumcoffee', instagram: 'https://instagram.com/premiumcoffee' },
    reviews: [],
    rating: 4.8,
    review_count: 47,
    view_count: 1200,
    likes_count: 220,
    booking_enabled: false,
    status: 'published',
    featured_until: '2025-12-31',
    legal_status: 'Registered',
    year_registered: 2019,
    verified: true,
    created_by: 'user1',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-20T15:30:00Z',
  },
  {
    id: '2',
    organization_id: 'org1',
    slug: 'tech-repair-services',
    title: 'Tech Repair Services',
    tagline: 'Expert repairs, affordable prices',
    description: 'We fix phones, laptops, and more with a fast turnaround.',
    category: 'Technology',
    tags: ['repair', 'electronics', 'certified'],
    location: { province: 'Western Area', district: 'Western Area Urban', chiefdom: 'Freetown' },
    district: 'Western Area Urban',
    chiefdom: 'Freetown',
    business_hours: baseHours,
    price_range: 'affordable',
    logo_url: 'https://api.dicebear.com/7.x/initials/svg?seed=Tech%20Repair%20Services',
    images: ['https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop'],
    videos: [],
    faqs: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'support@techrepair.com',
    contact_phone: '+232-76-000002',
    whatsapp_number: '+232-76-000002',
    website_url: 'https://techrepair.com',
    social_links: {},
    reviews: [],
    rating: 4.6,
    review_count: 23,
    view_count: 540,
    likes_count: 88,
    booking_enabled: true,
    status: 'published',
    verified: true,
    created_by: 'user1',
    created_at: '2024-01-10T12:00:00Z',
    updated_at: '2024-01-18T09:15:00Z',
  },
  {
    id: '3',
    organization_id: 'org1',
    slug: 'green-grocery',
    title: 'Green Grocery',
    tagline: 'Fresh and organic produce',
    description: 'Locally sourced fruits and vegetables delivered daily.',
    category: 'Retail',
    tags: ['grocery', 'organic', 'local'],
    location: { province: 'Northern', district: 'Bombali', chiefdom: 'Makeni' },
    district: 'Bombali',
    chiefdom: 'Makeni',
    business_hours: baseHours,
    price_range: 'moderate',
    logo_url: 'https://api.dicebear.com/7.x/initials/svg?seed=Green%20Grocery',
    images: ['https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=1200&auto=format&fit=crop'],
    videos: [],
    faqs: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'hello@greengrocery.sl',
    contact_phone: '+232-76-000003',
    whatsapp_number: '+232-76-000003',
    website_url: 'https://greengrocery.sl',
    social_links: {},
    reviews: [],
    rating: 4.2,
    review_count: 12,
    view_count: 210,
    likes_count: 34,
    booking_enabled: false,
    status: 'published',
    verified: true,
    created_by: 'user1',
    created_at: '2024-02-10T12:00:00Z',
    updated_at: '2024-02-18T09:15:00Z',
  },
  {
    id: '4',
    organization_id: 'org1',
    slug: 'fitness-hub',
    title: 'Fitness Hub',
    tagline: 'Your neighborhood gym',
    description: 'Modern equipment, expert trainers, and group classes.',
    category: 'Health & Fitness',
    tags: ['gym', 'fitness', 'classes'],
    location: { province: 'Southern', district: 'Bo', chiefdom: 'Tokei' },
    district: 'Bo',
    chiefdom: 'Tokei',
    business_hours: baseHours,
    price_range: 'premium',
    images: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&auto=format&fit=crop'],
    videos: [],
    faqs: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'join@fitnesshub.sl',
    contact_phone: '+232-76-000004',
    whatsapp_number: '+232-76-000004',
    website_url: 'https://fitnesshub.sl',
    social_links: {},
    reviews: [],
    rating: 4.4,
    review_count: 35,
    view_count: 780,
    likes_count: 140,
    booking_enabled: true,
    status: 'published',
    verified: true,
    created_by: 'user1',
    created_at: '2024-03-10T12:00:00Z',
    updated_at: '2024-03-18T09:15:00Z',
  },
  {
    id: '5',
    organization_id: 'org1',
    slug: 'artisan-bakery',
    title: 'Artisan Bakery',
    tagline: 'Baked fresh daily',
    description: 'Handcrafted breads and pastries made with care.',
    category: 'Food & Beverage',
    tags: ['bakery', 'bread', 'pastries'],
    location: { province: 'Eastern', district: 'Kono', chiefdom: 'Koidu' },
    district: 'Kono',
    chiefdom: 'Koidu',
    business_hours: baseHours,
    price_range: 'affordable',
    logo_url: 'https://api.dicebear.com/7.x/initials/svg?seed=Artisan%20Bakery',
    images: ['https://images.unsplash.com/photo-1511689660979-10d2b1aada49?w=1200&auto=format&fit=crop'],
    videos: [],
    faqs: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'hello@artisanbakery.sl',
    contact_phone: '+232-76-000005',
    whatsapp_number: '+232-76-000005',
    website_url: 'https://artisanbakery.sl',
    social_links: {},
    reviews: [],
    rating: 4.1,
    review_count: 9,
    view_count: 160,
    likes_count: 26,
    booking_enabled: false,
    status: 'published',
    verified: true,
    created_by: 'user1',
    created_at: '2024-04-10T12:00:00Z',
    updated_at: '2024-04-18T09:15:00Z',
  },
  {
    id: '6',
    organization_id: 'org1',
    slug: 'bluewave-salon',
    title: 'Bluewave Salon',
    tagline: 'Style that suits you',
    description: 'Professional hair care and styling services.',
    category: 'Services',
    tags: ['salon', 'beauty', 'hair'],
    location: { province: 'Western Area', district: 'Western Area Rural', chiefdom: 'Waterloo' },
    district: 'Western Area Rural',
    chiefdom: 'Waterloo',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'book@bluewave.salon',
    contact_phone: '+232-76-000006',
    whatsapp_number: '+232-76-000006',
    social_links: {},
    reviews: [],
    rating: 4.5,
    review_count: 18,
    view_count: 330,
    likes_count: 60,
    booking_enabled: true,
    status: 'published',
    verified: true,
    created_by: 'user1',
    created_at: '2024-05-10T12:00:00Z',
    updated_at: '2024-05-18T09:15:00Z',
  },
  {
    id: '7',
    organization_id: 'org1',
    slug: 'sunny-daycare',
    title: 'Sunny Daycare',
    tagline: 'Safe and caring environment',
    description: 'Experienced caregivers and engaging activities for kids.',
    category: 'Services',
    tags: ['daycare', 'children', 'education'],
    location: { province: 'Northern', district: 'Port Loko', chiefdom: 'Lunsar' },
    district: 'Port Loko',
    chiefdom: 'Lunsar',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'info@sunnydaycare.sl',
    contact_phone: '+232-76-000007',
    whatsapp_number: '+232-76-000007',
    social_links: {},
    reviews: [],
    rating: 4.3,
    review_count: 16,
    view_count: 300,
    likes_count: 55,
    booking_enabled: true,
    status: 'published',
    verified: true,
    created_by: 'user1',
    created_at: '2024-06-10T12:00:00Z',
    updated_at: '2024-06-18T09:15:00Z',
  },
  {
    id: '8',
    organization_id: 'org1',
    slug: 'coastal-tours',
    title: 'Coastal Tours',
    tagline: 'Explore the beautiful coastline',
    description: 'Guided tours and adventure packages.',
    category: 'Services',
    tags: ['tours', 'travel', 'adventure'],
    location: { province: 'Southern', district: 'Pujehun', chiefdom: 'Mano' },
    district: 'Pujehun',
    chiefdom: 'Mano',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'book@coastaltours.sl',
    contact_phone: '+232-76-000008',
    whatsapp_number: '+232-76-000008',
    social_links: {},
    reviews: [],
    rating: 4.0,
    review_count: 8,
    view_count: 150,
    likes_count: 20,
    booking_enabled: true,
    status: 'published',
    verified: true,
    created_by: 'user1',
    created_at: '2024-07-10T12:00:00Z',
    updated_at: '2024-07-18T09:15:00Z',
  },
  {
    id: '9',
    organization_id: 'org1',
    slug: 'city-pharmacy',
    title: 'City Pharmacy',
    tagline: 'Your health, our priority',
    description: 'Prescription services and health advice.',
    category: 'Health & Fitness',
    tags: ['pharmacy', 'health', 'medicine'],
    location: { province: 'Eastern', district: 'Kenema', chiefdom: 'Nongowa' },
    district: 'Kenema',
    chiefdom: 'Nongowa',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'contact@citypharmacy.sl',
    contact_phone: '+232-76-000009',
    whatsapp_number: '+232-76-000009',
    social_links: {},
    reviews: [],
    rating: 4.5,
    review_count: 40,
    view_count: 900,
    likes_count: 200,
    booking_enabled: false,
    status: 'published',
    verified: true,
    created_by: 'user1',
    created_at: '2024-08-10T12:00:00Z',
    updated_at: '2024-08-18T09:15:00Z',
  },
  {
    id: '10',
    organization_id: 'org1',
    slug: 'luna-bookstore',
    title: 'Luna Bookstore',
    tagline: 'Find your next read',
    description: 'Curated selection of books and stationery.',
    category: 'Retail',
    tags: ['books', 'stationery', 'reading'],
    location: { province: 'Western Area', district: 'Western Area Urban', chiefdom: 'Freetown' },
    district: 'Western Area Urban',
    chiefdom: 'Freetown',
    business_hours: baseHours,
    logo_url: 'https://api.dicebear.com/7.x/initials/svg?seed=Luna%20Bookstore',
    images: ['https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'hello@lunabookstore.sl',
    contact_phone: '+232-76-000010',
    whatsapp_number: '+232-76-000010',
    social_links: {},
    reviews: [],
    rating: 4.7,
    review_count: 51,
    view_count: 1300,
    likes_count: 260,
    booking_enabled: false,
    status: 'published',
    verified: true,
    created_by: 'user1',
    created_at: '2024-09-10T12:00:00Z',
    updated_at: '2024-09-18T09:15:00Z',
  },

  // 5 Draft
  {
    id: '11',
    organization_id: 'org1',
    slug: 'ocean-breeze-hotel',
    title: 'Ocean Breeze Hotel',
    tagline: 'Relax by the sea',
    description: 'Comfortable rooms and great views.',
    category: 'Services',
    tags: ['hotel', 'beach', 'relax'],
    location: { province: 'Western Area', district: 'Western Area Rural', chiefdom: 'York' },
    district: 'Western Area Rural',
    chiefdom: 'York',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1501117716987-c8e0bdde6651?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'stay@oceanbreeze.sl',
    contact_phone: '+232-76-000011',
    whatsapp_number: '+232-76-000011',
    social_links: {},
    reviews: [],
    rating: 0,
    review_count: 0,
    view_count: 0,
    likes_count: 0,
    booking_enabled: true,
    status: 'draft',
    verified: false,
    created_by: 'user1',
    created_at: '2024-10-10T12:00:00Z',
    updated_at: '2024-10-18T09:15:00Z',
  },
  {
    id: '12',
    organization_id: 'org1',
    slug: 'urban-cowork',
    title: 'Urban CoWork',
    tagline: 'Work. Connect. Grow.',
    description: 'Flexible coworking spaces for teams and freelancers.',
    category: 'Services',
    tags: ['cowork', 'office', 'startup'],
    location: { province: 'Western Area', district: 'Western Area Urban', chiefdom: 'Freetown' },
    district: 'Western Area Urban',
    chiefdom: 'Freetown',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'hello@urbancowork.sl',
    contact_phone: '+232-76-000012',
    whatsapp_number: '+232-76-000012',
    social_links: {},
    reviews: [],
    rating: 0,
    review_count: 0,
    booking_enabled: true,
    status: 'draft',
    verified: false,
    created_by: 'user1',
    created_at: '2024-10-12T12:00:00Z',
    updated_at: '2024-10-18T09:15:00Z',
  },
  {
    id: '13',
    organization_id: 'org1',
    slug: 'mountain-bikes',
    title: 'Mountain Bikes',
    tagline: 'Ride the trails',
    description: 'Bike sales, rentals, and repairs.',
    category: 'Retail',
    tags: ['bikes', 'outdoor', 'sports'],
    location: { province: 'Northern', district: 'Koinadugu', chiefdom: 'Kabala' },
    district: 'Koinadugu',
    chiefdom: 'Kabala',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'ride@mountainbikes.sl',
    contact_phone: '+232-76-000013',
    whatsapp_number: '+232-76-000013',
    social_links: {},
    reviews: [],
    rating: 0,
    review_count: 0,
    booking_enabled: false,
    status: 'draft',
    verified: false,
    created_by: 'user1',
    created_at: '2024-10-14T12:00:00Z',
    updated_at: '2024-10-18T09:15:00Z',
  },
  {
    id: '14',
    organization_id: 'org1',
    slug: 'heritage-museum',
    title: 'Heritage Museum',
    tagline: 'Discover our story',
    description: 'Exhibitions and cultural events.',
    category: 'Services',
    tags: ['museum', 'culture', 'history'],
    location: { province: 'Eastern', district: 'Kailahun', chiefdom: 'Kailahun' },
    district: 'Kailahun',
    chiefdom: 'Kailahun',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'visit@heritagemuseum.sl',
    contact_phone: '+232-76-000014',
    whatsapp_number: '+232-76-000014',
    social_links: {},
    reviews: [],
    rating: 0,
    review_count: 0,
    booking_enabled: false,
    status: 'draft',
    verified: false,
    created_by: 'user1',
    created_at: '2024-10-16T12:00:00Z',
    updated_at: '2024-10-18T09:15:00Z',
  },
  {
    id: '15',
    organization_id: 'org1',
    slug: 'savory-kitchen',
    title: 'Savory Kitchen',
    tagline: 'Taste the difference',
    description: 'Homestyle meals and catering services.',
    category: 'Food & Beverage',
    tags: ['restaurant', 'catering', 'local'],
    location: { province: 'Southern', district: 'Moyamba', chiefdom: 'Kaiyamba' },
    district: 'Moyamba',
    chiefdom: 'Kaiyamba',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1541542684-4a9c06b5a51b?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'order@savorykitchen.sl',
    contact_phone: '+232-76-000015',
    whatsapp_number: '+232-76-000015',
    social_links: {},
    reviews: [],
    rating: 0,
    review_count: 0,
    booking_enabled: true,
    status: 'draft',
    verified: false,
    created_by: 'user1',
    created_at: '2024-10-18T12:00:00Z',
    updated_at: '2024-10-18T12:30:00Z',
  },

  // 5 Archived
  {
    id: '16',
    organization_id: 'org1',
    slug: 'silver-screen-cinema',
    title: 'Silver Screen Cinema',
    tagline: 'Experience movies in style',
    description: 'Modern cinema with surround sound.',
    category: 'Services',
    tags: ['cinema', 'movies', 'entertainment'],
    location: { province: 'Western Area', district: 'Western Area Urban', chiefdom: 'Freetown' },
    district: 'Western Area Urban',
    chiefdom: 'Freetown',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'contact@silverscreen.sl',
    contact_phone: '+232-76-000016',
    whatsapp_number: '+232-76-000016',
    social_links: {},
    reviews: [],
    rating: 3.9,
    review_count: 14,
    booking_enabled: false,
    status: 'archived',
    verified: false,
    created_by: 'user1',
    created_at: '2023-11-10T12:00:00Z',
    updated_at: '2024-01-10T09:15:00Z',
  },
  {
    id: '17',
    organization_id: 'org1',
    slug: 'riverfront-cafe',
    title: 'Riverfront Cafe',
    tagline: 'Coffee by the river',
    description: 'Relaxing spot with scenic views.',
    category: 'Food & Beverage',
    tags: ['cafe', 'coffee', 'view'],
    location: { province: 'Northern', district: 'Tonkolili', chiefdom: 'Magburaka' },
    district: 'Tonkolili',
    chiefdom: 'Magburaka',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'hello@riverfrontcafe.sl',
    contact_phone: '+232-76-000017',
    whatsapp_number: '+232-76-000017',
    social_links: {},
    reviews: [],
    rating: 3.8,
    review_count: 7,
    booking_enabled: false,
    status: 'archived',
    verified: false,
    created_by: 'user1',
    created_at: '2023-10-10T12:00:00Z',
    updated_at: '2024-01-12T09:15:00Z',
  },
  {
    id: '18',
    organization_id: 'org1',
    slug: 'artisan-crafts',
    title: 'Artisan Crafts',
    tagline: 'Handmade with love',
    description: 'Local crafts and souvenirs.',
    category: 'Retail',
    tags: ['crafts', 'handmade', 'souvenirs'],
    location: { province: 'Eastern', district: 'Kono', chiefdom: 'Yengema' },
    district: 'Kono',
    chiefdom: 'Yengema',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1520975916090-3105956dac38?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'contact@artisancrafts.sl',
    contact_phone: '+232-76-000018',
    whatsapp_number: '+232-76-000018',
    social_links: {},
    reviews: [],
    rating: 3.6,
    review_count: 5,
    booking_enabled: false,
    status: 'archived',
    verified: false,
    created_by: 'user1',
    created_at: '2023-09-10T12:00:00Z',
    updated_at: '2024-01-14T09:15:00Z',
  },
  {
    id: '19',
    organization_id: 'org1',
    slug: 'tech-gadgets',
    title: 'Tech Gadgets',
    tagline: 'Latest and greatest',
    description: 'Electronics and accessories store.',
    category: 'Technology',
    tags: ['gadgets', 'electronics', 'accessories'],
    location: { province: 'Western Area', district: 'Western Area Urban', chiefdom: 'Freetown' },
    district: 'Western Area Urban',
    chiefdom: 'Freetown',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'shop@techgadgets.sl',
    contact_phone: '+232-76-000019',
    whatsapp_number: '+232-76-000019',
    social_links: {},
    reviews: [],
    rating: 3.5,
    review_count: 4,
    booking_enabled: false,
    status: 'archived',
    verified: false,
    created_by: 'user1',
    created_at: '2023-08-10T12:00:00Z',
    updated_at: '2024-01-16T09:15:00Z',
  },
  {
    id: '20',
    organization_id: 'org1',
    slug: 'golden-spa',
    title: 'Golden Spa',
    tagline: 'Relax and rejuvenate',
    description: 'Massage, sauna, and wellness services.',
    category: 'Services',
    tags: ['spa', 'wellness', 'massage'],
    location: { province: 'Southern', district: 'Bonthe', chiefdom: 'Shenge' },
    district: 'Bonthe',
    chiefdom: 'Shenge',
    business_hours: baseHours,
    images: ['https://images.unsplash.com/photo-1505575972945-2804b50a9e30?w=1200&auto=format&fit=crop'],
    videos: [],
    announcements: [],
    deals: [],
    menu: [],
    events: [],
    contact_email: 'relax@goldenspa.sl',
    contact_phone: '+232-76-000020',
    whatsapp_number: '+232-76-000020',
    social_links: {},
    reviews: [],
    rating: 3.7,
    review_count: 6,
    booking_enabled: true,
    status: 'archived',
    verified: false,
    created_by: 'user1',
    created_at: '2023-07-10T12:00:00Z',
    updated_at: '2024-01-18T09:15:00Z',
  },
];

// Helpers to enrich base listings so every section is present
const gallery = (seed: string) => Array.from({ length: 5 }, (_, i) => `https://picsum.photos/seed/${encodeURIComponent(seed)}-${i}/1280/720`);
const padImagesToFive = (existing: string[], seed: string) => {
  const safe = (existing || []).filter(Boolean);
  const needed = Math.max(0, 5 - safe.length);
  const extras = Array.from({ length: needed }, (_, i) => `https://picsum.photos/seed/${encodeURIComponent(seed)}-extra-${i}/1280/720`);
  return [...safe, ...extras].slice(0, 5);
};

const defaultFaqs = (slug: string) => [
  { id: `${slug}-faq-1`, question: 'What services do you offer?', answer: 'We offer a range of services tailored to your needs.', order: 1 },
  { id: `${slug}-faq-2`, question: 'What are your opening hours?', answer: 'Please see our business hours section for details.', order: 2 },
];

const defaultAnnouncement = (slug: string) => ({
  id: `${slug}-ann-1`,
  title: 'Welcome to our listing',
  content: 'This is a sample announcement showcasing this section.',
  type: 'info' as const,
  active: true,
  created_at: '2025-01-01T00:00:00Z',
});

const defaultDeal = (slug: string) => ({
  id: `${slug}-deal-1`,
  title: 'Intro Offer',
  description: '10% off your first purchase.',
  discount_type: 'percentage' as const,
  discount_value: 10,
  valid_from: '2025-01-01',
  valid_until: '2025-12-31',
  current_uses: 0,
  active: true,
});

const defaultMenuItem = (slug: string) => ({
  id: `${slug}-menu-1`,
  name: 'Sample Item',
  description: 'A featured item to demonstrate the menu section.',
  price: 9.99,
  category: 'General',
  available: true,
});

const defaultEvent = (slug: string) => ({
  id: `${slug}-event-1`,
  title: 'Open House',
  description: 'Come visit us and learn more about our services.',
  date: '2025-02-01',
  time: '10:00',
  registration_required: false,
  active: true,
});

const defaultTeamMembers = (slug: string) => ([
  {
    full_name: 'Amadu Koroma',
    position: 'Chief Executive Officer',
    photo_url: `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(slug)}%20CEO`,
  },
  {
    full_name: 'Mariatu Conteh',
    position: 'Operations Manager',
    photo_url: `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(slug)}%20Ops`,
  },
  {
    full_name: 'Joseph Kamara',
    position: 'Lead Specialist',
    photo_url: `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(slug)}%20Lead`,
  },
]);

const ensureAllSections = (l: Listing): Listing => {
  const slug = l.slug || l.title?.toLowerCase().replace(/\s+/g, '-') || 'listing';
  const images = (Array.isArray(l.images) ? l.images : []).filter(Boolean);
  const finalImages = padImagesToFive(images, slug);

  const socialLinks = l.social_links && Object.keys(l.social_links).length > 0
    ? l.social_links
    : {
        facebook: `https://facebook.com/${slug}`,
        instagram: `https://instagram.com/${slug}`,
        twitter: `https://twitter.com/${slug}`,
        linkedin: `https://linkedin.com/company/${slug}`,
        youtube: 'https://youtube.com/@easysearch',
        tiktok: 'https://tiktok.com/@easysearch',
      };

  return {
    ...l,
    images: finalImages,
    videos: l.videos && l.videos.length > 0 ? l.videos : ['https://www.youtube.com/watch?v=dQw4w9WgXcQ'],
    faqs: l.faqs && l.faqs.length > 0 ? l.faqs : defaultFaqs(slug),
    announcements: l.announcements && l.announcements.length > 0 ? l.announcements : [defaultAnnouncement(slug)],
    deals: l.deals && l.deals.length > 0 ? l.deals : [defaultDeal(slug)],
    menu: l.menu && l.menu.length > 0 ? l.menu : [defaultMenuItem(slug)],
    events: l.events && l.events.length > 0 ? l.events : [defaultEvent(slug)],
    contact_person: l.contact_person || {
      full_name: 'Jane Smith',
      position: 'Manager',
      phone: l.contact_phone || '+232-76-000000',
      email: l.contact_email || 'info@example.com',
    },
    team_members: l.team_members && l.team_members.length > 0 ? l.team_members : defaultTeamMembers(slug),
    target_audience: l.target_audience && l.target_audience.length > 0 ? l.target_audience : ['Students', 'Entrepreneurs'],
    social_links: socialLinks,
    full_address: l.full_address || `${l.title} Address, ${l.location?.chiefdom || ''}, ${l.location?.district || ''}`.replace(/,\s*,/g, ', '),
    vision_statement: l.vision_statement || 'Our vision is to serve our community with excellence.',
    mission_statement: l.mission_statement || 'Our mission is to deliver quality and value every day.',
    legal_status: l.legal_status || 'Registered',
    year_registered: l.year_registered || 2020,
  };
};

export const mockListings: Listing[] = baseMockListings.map(ensureAllSections);
